/* ============================================================
   OLK — ES TRANSLATIONS
   Public portfolio version
   ============================================================ */

window.OLK_TRANSLATIONS = window.OLK_TRANSLATIONS || {};
window.OLK_TRANSLATIONS.es = {
  "nav.home": "Inicio",
  "nav.services": "Servicios",
  "nav.portfolio": "Portafolio",
  "nav.products": "Productos",
  "nav.about": "Nosotros",
  "nav.contact": "Contacto",
  "footer.copy": "Copyright © 2026 OLK Web & SEO | Desarrollado por OLK Web & SEO",
  "home.hero.eyebrow": "Estudio de Diseño Web & SEO",
  "home.hero.title": "Diseñando y Desarrollando <span class=\"bracket\">&lt;</span><span class=\"accent\">Sitios Web de Alto Rendimiento</span><span class=\"bracket\">&gt;</span> que Impulsan el Crecimiento Real.",
  "home.hero.sub": "Diseño Web, Desarrollo Front-end, E-commerce, SEO y Tráfico de Pago para marcas de todo el mundo.",
  "home.hero.cta1": "Ver Proyectos",
  "home.hero.cta2": "Contáctanos",
  "home.brands.label": "Marcas que confiaron en nosotros",
  "home.services.label": "Lo que hacemos",
  "home.services.title": "Ayudamos a las marcas a crear experiencias digitales rápidas, escalables y orientadas a la conversión.",
  "home.services.sub": "Del diseño y desarrollo al tráfico y SEO — todo construido con el rendimiento en mente.",
  "home.services.card1": "Diseño Web & Desarrollo Front-End",
  "home.services.card2": "Configuración de E-Commerce",
  "home.services.card3": "Tráfico de Pago (Meta Ads)",
  "home.services.card4": "SEO (Optimización en Motores de Búsqueda) — Google",
  "home.services.cta": "Ver Todos los Servicios",
  "home.portfolio.label": "Proyectos seleccionados",
  "home.portfolio.title": "Una selección de proyectos creados para diferentes industrias, mercados y modelos de negocio.",
  "home.portfolio.sub": "Siempre enfocados en claridad, usabilidad y resultados.",
  "home.portfolio.p1.label": "Portafolio Fotográfico",
  "home.portfolio.p2.label": "Marca de Bebidas Premium",
  "home.portfolio.p3.label": "Landing Page de Newsletter",
  "home.portfolio.p4.label": "Marca Automotriz Premium",
  "home.portfolio.cta": "Ver Portafolio Completo",
  "home.about.label": "Sobre nosotros",
  "home.about.title": "Experiencia que va más allá del diseño",
  "home.about.body": "Hemos creado sitios web de alto rendimiento y estrategias digitales en distintas industrias, combinando diseño, tecnología y estrategia de marketing para ofrecer resultados reales.<br><br>Nuestro enfoque se centra en la experiencia del usuario, la velocidad y la conversión — garantizando que cada proyecto sea no solo visualmente potente, sino estratégicamente efectivo.",
  "home.about.s1.label": "Años de experiencia profesional",
  "home.about.s2.label": "Proyectos entregados globalmente",
  "home.about.s3.label": "Enfoque orientado al rendimiento",
  "home.about.s4.label": "Industrias atendidas en todo el mundo",
  "home.teaser1.title": "Productos Digitales",
  "home.teaser1.body": "Templates de landing page orientados a la conversión y productos de diseño listos para usar, creados para acelerar lanzamientos y mejorar resultados.",
  "home.teaser1.cta": "Explorar Productos",
  "home.teaser2.title": "Iniciar un Proyecto",
  "home.teaser2.body": "¿Listo para construir algo que realmente convierte? Hablemos de tus objetivos y creemos una experiencia digital de alto rendimiento.",
  "home.teaser2.cta": "Contáctanos",
  "home.cta.title": "Construyamos algo que realmente funcione.",
  "home.cta.sub": "Si buscas un sitio web construido con claridad, rendimiento y crecimiento a largo plazo — hablemos.",
  "home.cta.btn": "Contáctanos",
  "srv.hero.label": "Lo que ofrecemos",
  "srv.hero.title": "<span class=\"accent\">Nuestros</span> Servicios",
  "srv.hero.sub": "Ayudamos a las marcas a diseñar, desarrollar y crecer con sitios web de alto rendimiento. Nuestros servicios cubren todo el proceso — de la estructura y el código al tráfico y la visibilidad — siempre enfocados en resultados.",
  "srv.intro": "Cada proyecto se aborda con una <strong>mentalidad full-stack</strong>: consideramos diseño, desarrollo y marketing como un sistema unificado. El resultado es un sitio que se ve bien, carga rápido y <strong>convierte</strong>.",
  "srv.s1.num": "01",
  "srv.s1.title": "Diseño Web & Desarrollo Front-End",
  "srv.s1.desc": "Diseño y desarrollo de sitios web modernos y responsivos orientados al rendimiento y la conversión.",
  "srv.s1.f1": "Diseños enfocados en UX/UI",
  "srv.s1.f2": "Código front-end limpio y escalable",
  "srv.s1.f3": "Diseño responsivo para todos los dispositivos",
  "srv.s1.f4": "Optimización de rendimiento y velocidad de carga",
  "srv.s1.vtag": "De Figma al código pixel-perfect",
  "srv.s1.vnote": "Cada interfaz se crea con atención al flujo del usuario, la jerarquía visual y los resultados de conversión medibles.",
  "srv.s2.num": "02",
  "srv.s2.title": "SEO (Search Engine Optimization)",
  "srv.s2.desc": "SEO técnico y on-page para mejorar la visibilidad y el crecimiento orgánico a largo plazo.",
  "srv.s2.f1": "Fundamentos de SEO técnico",
  "srv.s2.f2": "Optimización on-page",
  "srv.s2.f3": "Estructura de contenido lista para SEO",
  "srv.s2.f4": "Optimización de blog y páginas",
  "srv.s2.vtag": "Posiciona más alto. Crece orgánicamente.",
  "srv.s2.vnote": "Diseñado para atraer tráfico calificado con el tiempo — no solo rankings, sino visitantes que realmente se convierten en clientes.",
  "srv.s3.num": "03",
  "srv.s3.title": "Perfil de Empresa en Google",
  "srv.s3.desc": "Visibilidad local creada para generar crecimiento, no solo clics.",
  "srv.s3.f1": "Configuración del Perfil de Empresa",
  "srv.s3.f2": "SEO local y alineación del perfil",
  "srv.s3.f3": "Optimización enfocada en conversión",
  "srv.s3.vtag": "Visibilidad local que convierte",
  "srv.s3.vnote": "Perfiles pensados para el recorrido local — desde la primera búsqueda hasta la decisión final de contacto.",
  "srv.s4.num": "04",
  "srv.s4.title": "Configuración de E-Commerce",
  "srv.s4.desc": "Configuración y optimización de tiendas online diseñadas para escalar y convertir.",
  "srv.s4.f1": "Tiendas Shopify & WooCommerce",
  "srv.s4.f2": "Estructura de productos y colecciones",
  "srv.s4.f3": "Optimización del checkout",
  "srv.s4.f4": "Diseños orientados a la conversión",
  "srv.s4.vtag": "Tiendas construidas para vender",
  "srv.s4.vnote": "Cada detalle del flujo de compra está diseñado para reducir fricciones y maximizar los ingresos por visitante.",
  "srv.cta.title": "¿Listo para comenzar tu proyecto?",
  "srv.cta.sub": "Hablemos de lo que tu marca necesita — y construyámoslo de la manera correcta.",
  "srv.cta.btn": "Contáctanos",
  "pf.hero.label": "Proyectos del portafolio",
  "pf.hero.title": "<span class=\"accent\">Proyectos</span> Seleccionados",
  "pf.hero.sub": "Proyectos desarrollados para marcas, creadores y empresas en múltiples industrias. Cada uno representa un enfoque reflexivo de diseño, código y estrategia — centrado en claridad, rendimiento y crecimiento a largo plazo.",
  "pf.p1.num": "Proyecto 01",
  "pf.p1.cat": "Portafolio Fotográfico",
  "pf.p1.title": "Sitio Web de Portafolio Fotográfico",
  "pf.p1.desc": "Un concepto completo de sitio de portafolio creado para presentar trabajos visuales con una estética limpia, editorial y enfocada en impacto, claridad y experiencia del usuario.",
  "pf.p1.t1": "Diseño Web",
  "pf.p1.t2": "Desarrollo Front-End",
  "pf.p1.t3": "Portafolio",
  "pf.p1.link": "Ver Proyecto",
  "pf.p2.num": "Proyecto 02",
  "pf.p2.cat": "Marca de Bebidas Premium",
  "pf.p2.title": "Landing Page para Marca de Bebidas Premium",
  "pf.p2.desc": "Un concepto de landing page de alta conversión para una marca de bebidas premium, estructurado para apoyar la presentación del producto, el interés de distribuidores y el crecimiento comercial.",
  "pf.p2.t1": "Landing Page",
  "pf.p2.t2": "E-Commerce",
  "pf.p2.t3": "Conversión CRO",
  "pf.p2.link": "Ver Proyecto",
  "pf.p3.num": "Proyecto 03",
  "pf.p3.cat": "Landing Page de Newsletter",
  "pf.p3.title": "Landing Page para Suscripción a Newsletter",
  "pf.p3.desc": "Un concepto de landing page enfocado en newsletter, diseñado para comunicar valor y generar registros con un diseño claro, directo y estructura de copy persuasiva.",
  "pf.p3.t1": "Landing Page",
  "pf.p3.t2": "Newsletter",
  "pf.p3.t3": "Generación de Leads",
  "pf.p3.link": "Ver Proyecto",
  "pf.p4.num": "Proyecto 04",
  "pf.p4.cat": "Marca Automotriz Premium",
  "pf.p4.title": "Landing Page para Marca Automotriz Premium",
  "pf.p4.desc": "Un concepto sofisticado de landing page para presentar servicios automotrices de alta gama con claridad, confianza y una experiencia digital premium.",
  "pf.p4.t1": "Landing Page",
  "pf.p4.t2": "Lujo",
  "pf.p4.t3": "Automotriz",
  "pf.p4.link": "Ver Proyecto",
  "pf.cta.title": "¿Tienes un proyecto en mente?",
  "pf.cta.sub": "Construyamos algo que rinda tan bien como se ve.",
  "pf.cta.btn": "Contáctanos",
  "pr.f1.kicker": "Activos digitales",
  "pr.f1.title": "Templates de Figma, Mockups & Productos de Diseño",
  "pr.f1.desc": "Productos digitales premium creados para la conversión. Usa estos templates para lanzar más rápido, presentar mejor tu trabajo y mejorar tus resultados sin empezar desde cero.",
  "pr.f1.btn1": "Comprar Ahora",
  "pr.f1.btn2": "¿Dudas?",
  "pr.f2.kicker": "Landing Pages",
  "pr.f2.title": "Templates de Landing Page Listos para Convertir",
  "pr.f2.desc": "Templates de landing page totalmente estructurados y creados para el rendimiento. Cada template está diseñado con principios de CRO — títulos optimizados, CTAs claros y diseños que guían al visitante hacia la conversión.",
  "pr.f2.btn1": "Comprar Ahora",
  "pr.cta.title": "¿Necesitas algo hecho a medida?",
  "pr.cta.sub": "Desarrollamos experiencias digitales personalizadas para marcas que quieren crecer. Hablemos.",
  "pr.cta.btn": "Contáctanos",
  "ab.who.eyebrow": "Sobre OLK",
  "ab.who.title": "Quiénes Somos",
  "ab.who.p1": "OLK es un estudio de diseño web y desarrollo front-end orientado al rendimiento, enfocado en crear experiencias digitales de alta conversión.",
  "ab.who.p2": "Trabajamos con empresas que quieren más que un sitio web — quieren crecimiento. Combinando diseño, tecnología y estrategia de marketing, creamos sitios web, landing pages y estructuras de SEO diseñados para rendir.",
  "ab.who.p3": "Nuestro trabajo se centra en la experiencia del usuario, la velocidad y la conversión, asegurando que cada proyecto sea no solo visualmente sólido, sino estratégicamente efectivo.",
  "ab.who.p4": "Ayudamos a las marcas a convertir el tráfico en ingresos.",
  "ab.why.eyebrow": "Por qué OLK",
  "ab.why.title": "Por qué Elegirnos",
  "ab.why.subtitle": "Enfoque de Rendimiento Primero",
  "ab.why.body": "No solo construimos sitios web — construimos activos digitales diseñados para generar leads, aumentar conversiones y escalar negocios.<br><br>Nuestro proceso combina CRO (Optimización de Tasa de Conversión), desarrollo front-end limpio y decisiones basadas en datos para ofrecer resultados reales.",
  "ab.why.s1.num": "6+",
  "ab.why.s1.label": "Años de Experiencia",
  "ab.why.s2.num": "100+",
  "ab.why.s2.label": "Proyectos Entregados",
  "ab.why.s3.label": "Enfoque en Clientes Globales",
  "ab.val.label": "Nuestro enfoque",
  "ab.val.title": "Lo que nos diferencia",
  "ab.val.sub": "Tratamos cada proyecto como un activo estratégico — no solo un entregable de diseño.",
  "ab.v1.title": "Rendimiento Primero",
  "ab.v1.desc": "Cada decisión — del diseño a la estructura del código — se toma con velocidad, usabilidad y conversión en mente. Construimos para resultados, no solo para estética.",
  "ab.v2.title": "Diseño Orientado a CRO",
  "ab.v2.desc": "Aplicamos principios de Optimización de Tasa de Conversión en todo el proceso de diseño — mapeando flujos de usuario, reduciendo fricciones y alineando cada elemento a un objetivo de negocio claro.",
  "ab.v3.title": "Alcance Global",
  "ab.v3.desc": "Trabajamos con empresas listas para escalar local e internacionalmente, creando experiencias digitales que se comunican claramente en diferentes mercados y culturas.",
  "ab.cta.title": "¿Listo para trabajar con nosotros?",
  "ab.cta.sub": "Construyamos una experiencia digital que realmente rinda y haga crecer tu negocio.",
  "ab.cta.btn": "Contáctanos",
  "ct.info.label": "Ponte en contacto",
  "ct.info.title": "Nos encantaría escuchar sobre tu proyecto",
  "ct.info.desc": "Ya sea un nuevo sitio web, una landing page, soporte de SEO o una estrategia digital completa — estamos listos para ayudar. Comparte tus objetivos y prepararemos una propuesta personalizada.",
  "ct.card1.label": "Correo",
  "ct.card1.note": "Solemos responder en menos de 24 horas",
  "ct.card2.label": "WhatsApp",
  "ct.card2.value": "Chatea directamente con nosotros",
  "ct.card2.note": "Respuestas rápidas durante el horario laboral",
  "ct.card3.label": "Ubicación",
  "ct.card3.value": "Remoto — Mundial",
  "ct.card3.note": "Trabajamos con clientes en todo el mundo",
  "ct.form.title": "Envía un mensaje",
  "ct.form.name": "Tu nombre",
  "ct.form.name.ph": "Juan García",
  "ct.form.email": "Correo electrónico",
  "ct.form.email.ph": "tu@empresa.com",
  "ct.form.company": "Empresa / URL del sitio",
  "ct.form.company.ph": "tuempresa.com",
  "ct.form.service": "Servicio que necesitas",
  "ct.form.svc.default": "Selecciona un servicio...",
  "ct.form.svc.web": "Diseño Web & Desarrollo Front-End",
  "ct.form.svc.seo": "SEO (Google)",
  "ct.form.svc.ecom": "Configuración de E-Commerce",
  "ct.form.svc.ads": "Tráfico de Pago (Meta Ads)",
  "ct.form.svc.full": "Estrategia Digital Completa",
  "ct.form.svc.other": "Otro",
  "ct.form.msg": "Cuéntanos sobre tu proyecto",
  "ct.form.msg.ph": "Describe tus objetivos, plazos y cualquier detalle relevante...",
  "ct.form.submit": "Formulario Demo →",
  "ct.form.note": "Sin spam. Sin compromisos. Solo una conversación sobre tu proyecto.",
  "case.fayson.label": "Proyecto de Portafolio",
  "case.fayson.hero.title": "Sitio de Portafolio para <span class=\"accent\">Fotografía Profesional</span>",
  "case.fayson.hero.sub": "Una galería digital visual-first diseñada para mostrar excelencia artística y capturar momentos profesionales.",
  "case.fayson.overview.label": "Visión General",
  "case.fayson.overview.title": "Excelencia visual con navegación de alto rendimiento.",
  "case.fayson.overview.text": "Este proyecto fue desarrollado como un concepto de plataforma premium para presentar fotografía profesional. La estructura prioriza calidad visual, navegación fluida y una experiencia de presentación clara.",
  "case.fayson.d1": "Estructura de galería personalizada",
  "case.fayson.d2": "Optimización de imágenes en alta resolución",
  "case.fayson.d3": "Diseño visual responsivo",
  "case.fayson.d4": "Transiciones suaves y front-end orientado al rendimiento",
  "case.fayson.strategy.label": "La Estrategia",
  "case.fayson.strategy.title": "Diseñar para el ojo del artista.",
  "case.fayson.strategy.text1": "El diseño fue planificado para dejar que las fotografías hablen por sí mismas. Reducimos el ruido visual y creamos un flujo minimalista que guía al visitante por el mejor trabajo del fotógrafo.",
  "case.fayson.strategy.text2": "La dirección visual combina tipografía fuerte, estética premium oscura y bloques de contenido claros para crear una experiencia moderna y memorable.",
  "case.fayson.gallery.label": "Pantallas Visuales",
  "case.fayson.gallery.title": "Vistas seleccionadas del proyecto",
  "case.fayson.outcome.label": "Resultado",
  "case.fayson.outcome.title": "Un escenario refinado para fotografía de alto nivel.",
  "case.fayson.outcome.text": "El resultado final es un portafolio profesional que fortalece el posicionamiento de marca y ofrece una experiencia fluida para potenciales clientes y colaboradores.",
  "case.fayson.back": "Volver al Portafolio",
  "case.mansao.label": "Proyecto de Portafolio",
  "case.mansao.hero.title": "Landing Page de Alta Conversión para <span class=\"accent\">Bebidas Premium</span>",
  "case.mansao.hero.sub": "Una experiencia estratégica de ventas creada para conectar una audiencia digital con la distribución de bebidas premium.",
  "case.mansao.overview.label": "Visión General",
  "case.mansao.overview.title": "Diseño orientado a la conversión para una gran marca digital.",
  "case.mansao.overview.text": "Creada para una marca de bebidas premium, esta landing page conceptual simplifica la comunicación B2B y la presentación del producto, transformando atención digital en intención comercial clara para distribuidores y minoristas.",
  "case.mansao.d1": "Jerarquía de contenido de alta conversión",
  "case.mansao.d2": "Integración de flujo de ventas B2B",
  "case.mansao.d3": "Arquitectura digital escalable",
  "case.mansao.d4": "Interfaz enfocada en rendimiento",
  "case.mansao.strategy.label": "La Estrategia",
  "case.mansao.strategy.title": "Convirtiendo gran influencia en ventas.",
  "case.mansao.strategy.text1": "Creamos un camino estratégico que guía al usuario desde el reconocimiento social de la marca hasta la intención final de compra.",
  "case.mansao.strategy.text2": "La dirección visual utiliza elementos fuertes y bloques de contenido claros para mantener la identidad energética de la marca, mientras presenta un entorno B2B profesional y confiable.",
  "case.mansao.gallery.label": "Pantallas Visuales",
  "case.mansao.gallery.title": "Vistas seleccionadas del proyecto",
  "case.mansao.outcome.label": "Resultado",
  "case.mansao.outcome.title": "Un poderoso motor de ventas para un gigante digital.",
  "case.mansao.outcome.text": "Esta landing page sirve como una base sólida para campañas de marketing, ayudando a convertir tráfico digital en oportunidades comerciales y una comunicación más clara con socios.",
  "case.mansao.back": "Volver al Portafolio",
  "case.economy.label": "Proyecto de Portafolio",
  "case.economy.hero.title": "Landing Page Newsletter para <span class=\"accent\">Insights Digitales</span>",
  "case.economy.hero.sub": "Una landing page dinámica diseñada para convertir visitantes en suscriptores informados.",
  "case.economy.overview.label": "Visión General",
  "case.economy.overview.title": "Velocidad y claridad para el futuro de las finanzas.",
  "case.economy.overview.text": "Diseñado como concepto de landing page para newsletter, este proyecto se centra en la entrega rápida de información y flujos de suscripción simples para una audiencia digital de ritmo acelerado.",
  "case.economy.d1": "Implementación rápida de suscripción",
  "case.economy.d2": "Jerarquía enfocada en contenido",
  "case.economy.d3": "Integración estética Web3",
  "case.economy.d4": "Optimizado para velocidad y navegación móvil",
  "case.economy.strategy.label": "La Estrategia",
  "case.economy.strategy.title": "Reduciendo fricción en un mercado acelerado.",
  "case.economy.strategy.text1": "La estrategia se centró en una propuesta de valor clara: mantenerse un paso adelante. Cada bloque fue ubicado para destacar la exclusividad de los insights del newsletter.",
  "case.economy.strategy.text2": "La dirección visual combina tipografía moderna con una estética limpia y tecnológica para crear un centro de información confiable y profesional.",
  "case.economy.gallery.label": "Pantallas Visuales",
  "case.economy.gallery.title": "Vistas seleccionadas del proyecto",
  "case.economy.outcome.label": "Resultado",
  "case.economy.outcome.title": "Una puerta directa hacia la economía Web3.",
  "case.economy.outcome.text": "El proyecto ofrece una experiencia de suscripción rápida y estratégica que impulsa el crecimiento de la comunidad y refuerza el valor del contenido digital especializado.",
  "case.economy.back": "Volver al Portafolio",
  "case.mythoss.label": "Proyecto de Portafolio",
  "case.mythoss.hero.title": "Landing Page Sofisticada para <span class=\"accent\">Servicios Automotrices Premium</span>",
  "case.mythoss.hero.sub": "Una vitrina digital exclusiva para cuidado automotriz de alta gama, enfatizando rendimiento y lujo.",
  "case.mythoss.overview.label": "Visión General",
  "case.mythoss.overview.title": "Exclusividad y precisión en cada detalle digital.",
  "case.mythoss.overview.text": "Este proyecto presenta servicios automotrices premium para propietarios de vehículos de alta gama. La página destaca valor, confianza, calidad y compromiso con el rendimiento automotriz.",
  "case.mythoss.d1": "Diseño de identidad visual premium",
  "case.mythoss.d2": "Diseño enfocado en servicios",
  "case.mythoss.d3": "Secciones para generar confianza",
  "case.mythoss.d4": "Experiencia móvil de lujo mobile-first",
  "case.mythoss.strategy.label": "La Estrategia",
  "case.mythoss.strategy.title": "Comunicando lujo mediante precisión digital.",
  "case.mythoss.strategy.text1": "Cada decisión de diseño fue tomada para reflejar la calidad de los servicios automotrices. Utilizamos una estética premium oscura para acompañar los vehículos de alta gama atendidos.",
  "case.mythoss.strategy.text2": "La dirección visual combina tipografía fuerte con bloques de contenido claros y sofisticados para crear una experiencia digital moderna y memorable.",
  "case.mythoss.gallery.label": "Pantallas Visuales",
  "case.mythoss.gallery.title": "Vistas seleccionadas del proyecto",
  "case.mythoss.outcome.label": "Resultado",
  "case.mythoss.outcome.title": "Un estándar digital para el cuidado automotriz premium.",
  "case.mythoss.outcome.text": "Una presencia digital sofisticada que refuerza un posicionamiento premium, genera confianza y comunica excelencia en el sector automotriz de alta gama.",
  "case.mythoss.back": "Volver al Portafolio",
  "pr.f2.btn2": "¿Dudas?"
};
