/* ============================================================
   OLK — EN TRANSLATIONS
   Public portfolio version
   ============================================================ */

window.OLK_TRANSLATIONS = window.OLK_TRANSLATIONS || {};
window.OLK_TRANSLATIONS.en = {
  "nav.home": "Home",
  "nav.services": "Services",
  "nav.portfolio": "Portfolio",
  "nav.products": "Products",
  "nav.about": "About",
  "nav.contact": "Contact",
  "footer.copy": "Copyright © 2026 OLK Web & SEO | Powered by OLK Web & SEO",
  "home.hero.eyebrow": "Web Design & SEO Studio",
  "home.hero.title": "Designing and Developing <span class=\"bracket\">&lt;</span><span class=\"accent\">High-Performance Websites</span><span class=\"bracket\">&gt;</span> that Drive Real Business Growth.",
  "home.hero.sub": "Web Design, Front-end Development, E-commerce, SEO and Paid Traffic for brands all around the world.",
  "home.hero.cta1": "View Work",
  "home.hero.cta2": "Get in Touch",
  "home.brands.label": "Brands that trusted us",
  "home.services.label": "What we do",
  "home.services.title": "We help brands build fast, scalable and conversion-focused digital experiences.",
  "home.services.sub": "From design and development to traffic and SEO — everything built with performance in mind.",
  "home.services.card1": "Web Design & Front-End Development",
  "home.services.card2": "E-Commerce Setup",
  "home.services.card3": "Paid Traffic (Meta Ads)",
  "home.services.card4": "SEO (Search Engine Optimization) — Google",
  "home.services.cta": "View All Services",
  "home.portfolio.label": "Selected work",
  "home.portfolio.title": "A selection of projects built for different industries, markets and business models.",
  "home.portfolio.sub": "Always focused on clarity, usability and results.",
  "home.portfolio.p1.label": "Photography Portfolio",
  "home.portfolio.p2.label": "Premium Drinks Brand",
  "home.portfolio.p3.label": "Newsletter Landing Page",
  "home.portfolio.p4.label": "Premium Automotive Brand",
  "home.portfolio.cta": "View Full Portfolio",
  "home.about.label": "About us",
  "home.about.title": "Experience that goes beyond design",
  "home.about.body": "We've been building high-performance websites and digital strategies across different industries, combining design, technology and marketing strategy to deliver real results.<br><br>Our approach focuses on user experience, speed and conversion — ensuring every project is not only visually strong, but strategically effective.",
  "home.about.s1.label": "Years of professional experience",
  "home.about.s2.label": "Projects delivered globally",
  "home.about.s3.label": "Performance-focused approach",
  "home.about.s4.label": "Industries served worldwide",
  "home.teaser1.title": "Digital Products",
  "home.teaser1.body": "Conversion-focused landing page templates and ready-to-use design products, created to speed up launches and improve results.",
  "home.teaser1.cta": "Explore Products",
  "home.teaser2.title": "Start a Project",
  "home.teaser2.body": "Ready to build something that actually converts? Let's talk about your goals and create a digital experience that performs.",
  "home.teaser2.cta": "Contact Us",
  "home.cta.title": "Let's build something that actually works.",
  "home.cta.sub": "If you're looking for a website built with clarity, performance and long-term growth in mind — let's talk.",
  "home.cta.btn": "Contact Us",
  "srv.hero.label": "What we offer",
  "srv.hero.title": "<span class=\"accent\">Our</span> Services",
  "srv.hero.sub": "We help brands design, build and grow high-performance websites. Our services cover the full process — from structure and code to traffic and visibility — always focused on results.",
  "srv.intro": "Every project is approached with a <strong>full-stack mindset</strong>: we consider design, development and marketing as one unified system. The result is a website that looks great, loads fast and <strong>converts</strong>.",
  "srv.s1.num": "01",
  "srv.s1.title": "Web Design & Front-End Development",
  "srv.s1.desc": "Design and development of modern, responsive websites built for performance and conversion.",
  "srv.s1.f1": "UX/UI focused layouts",
  "srv.s1.f2": "Clean, scalable front-end code",
  "srv.s1.f3": "Responsive design for all devices",
  "srv.s1.f4": "Performance and loading speed optimization",
  "srv.s1.vtag": "From Figma to pixel-perfect code",
  "srv.s1.vnote": "Every interface is crafted with attention to user flow, visual hierarchy and measurable conversion outcomes.",
  "srv.s2.num": "02",
  "srv.s2.title": "SEO (Search Engine Optimization)",
  "srv.s2.desc": "Technical and on-page SEO to improve visibility and long-term organic growth.",
  "srv.s2.f1": "Technical SEO foundations",
  "srv.s2.f2": "On-page optimization",
  "srv.s2.f3": "SEO-ready content structure",
  "srv.s2.f4": "Blog and page optimization",
  "srv.s2.vtag": "Rank higher. Grow organically.",
  "srv.s2.vnote": "Built to attract qualified traffic over time — not just rankings, but visitors who actually convert into customers.",
  "srv.s3.num": "03",
  "srv.s3.title": "Google Business Profile",
  "srv.s3.desc": "Local visibility built to support growth, not just clicks.",
  "srv.s3.f1": "Google Business Profile setup",
  "srv.s3.f2": "Local SEO and profile alignment",
  "srv.s3.f3": "Conversion-driven optimization",
  "srv.s3.vtag": "Local visibility that converts",
  "srv.s3.vnote": "Profiles designed with the local journey in mind — from the first search to the final contact decision.",
  "srv.s4.num": "04",
  "srv.s4.title": "E-Commerce Setup",
  "srv.s4.desc": "Setup and optimization of online stores designed to scale and convert.",
  "srv.s4.f1": "Shopify & WooCommerce stores",
  "srv.s4.f2": "Product and collection structure",
  "srv.s4.f3": "Checkout optimization",
  "srv.s4.f4": "Conversion-focused layouts",
  "srv.s4.vtag": "Stores built to sell",
  "srv.s4.vnote": "Every detail of the purchase flow is engineered to reduce friction and maximize revenue per visitor.",
  "srv.cta.title": "Ready to start your project?",
  "srv.cta.sub": "Let's talk about what your brand needs — and build it the right way.",
  "srv.cta.btn": "Contact Us",
  "pf.hero.label": "Portfolio projects",
  "pf.hero.title": "<span class=\"accent\">Selected</span> Work",
  "pf.hero.sub": "Projects developed for brands, creators and businesses across multiple industries. Each one represents a thoughtful approach to design, code and strategy — focused on clarity, performance and long-term growth.",
  "pf.p1.num": "Project 01",
  "pf.p1.cat": "Photography Portfolio",
  "pf.p1.title": "Photography Portfolio Website",
  "pf.p1.desc": "A complete portfolio website concept designed to showcase visual work with a clean, editorial aesthetic focused on impact, clarity and user experience.",
  "pf.p1.t1": "Web Design",
  "pf.p1.t2": "Front-End Dev",
  "pf.p1.t3": "Portfolio",
  "pf.p1.link": "View Project",
  "pf.p2.num": "Project 02",
  "pf.p2.cat": "Premium Drinks Brand",
  "pf.p2.title": "Landing Page for a Premium Drinks Brand",
  "pf.p2.desc": "A high-converting landing page concept for a premium beverage brand, structured to support product presentation, distributor interest and commercial growth.",
  "pf.p2.t1": "Landing Page",
  "pf.p2.t2": "E-Commerce",
  "pf.p2.t3": "Conversion CRO",
  "pf.p2.link": "View Project",
  "pf.p3.num": "Project 03",
  "pf.p3.cat": "Newsletter Landing Page",
  "pf.p3.title": "Newsletter Subscription Landing Page",
  "pf.p3.desc": "A focused newsletter landing page concept designed to communicate value and drive signups with a clear, distraction-free layout and compelling copy structure.",
  "pf.p3.t1": "Landing Page",
  "pf.p3.t2": "Newsletter",
  "pf.p3.t3": "Lead Gen",
  "pf.p3.link": "View Project",
  "pf.p4.num": "Project 04",
  "pf.p4.cat": "Premium Automotive Brand",
  "pf.p4.title": "Landing Page for a Premium Automotive Brand",
  "pf.p4.desc": "A sophisticated landing page concept designed to present high-end automotive services with clarity, trust and a premium digital experience.",
  "pf.p4.t1": "Landing Page",
  "pf.p4.t2": "Luxury",
  "pf.p4.t3": "Automotive",
  "pf.p4.link": "View Project",
  "pf.cta.title": "Have a project in mind?",
  "pf.cta.sub": "Let's build something that performs as well as it looks.",
  "pf.cta.btn": "Contact Us",
  "pr.f1.kicker": "Digital assets",
  "pr.f1.title": "Figma Templates, Mockups & Design Products",
  "pr.f1.desc": "Premium digital products crafted for conversion. Use these templates to launch faster, present your work better and improve your results without starting from scratch.",
  "pr.f1.btn1": "Buy Now",
  "pr.f1.btn2": "Any Doubts?",
  "pr.f2.kicker": "Landing Pages",
  "pr.f2.title": "Conversion-Ready Landing Page Templates",
  "pr.f2.desc": "Fully structured landing page templates built for performance. Each template is designed with CRO principles — optimized headlines, clear CTAs and layouts that guide the visitor towards conversion.",
  "pr.f2.btn1": "Buy Now",
  "pr.cta.title": "Need something custom-built?",
  "pr.cta.sub": "We build tailored digital experiences for brands that want to grow. Let's talk.",
  "pr.cta.btn": "Contact Us",
  "ab.who.eyebrow": "About OLK",
  "ab.who.title": "Who We Are",
  "ab.who.p1": "OLK is a performance-driven web design and front-end development studio focused on building high-converting digital experiences.",
  "ab.who.p2": "We partner with businesses that want more than just a website — they want growth. By combining design, technology and marketing strategy, we create websites, landing pages and SEO structures that are built to perform.",
  "ab.who.p3": "Our work is focused on user experience, speed and conversion, ensuring every project is not only visually strong, but strategically effective.",
  "ab.who.p4": "We help brands turn traffic into revenue.",
  "ab.why.eyebrow": "Why OLK",
  "ab.why.title": "Why Choose Us",
  "ab.why.subtitle": "Performance First Approach",
  "ab.why.body": "We don't just build websites — we build digital assets designed to generate leads, increase conversions and scale businesses.<br><br>Our process combines CRO (Conversion Rate Optimization), clean front-end development and data-driven decisions to deliver real results.",
  "ab.why.s1.num": "6+",
  "ab.why.s1.label": "Years Experience",
  "ab.why.s2.num": "100+",
  "ab.why.s2.label": "Projects Delivered",
  "ab.why.s3.label": "Global Client Focus",
  "ab.val.label": "Our approach",
  "ab.val.title": "What makes us different",
  "ab.val.sub": "We treat every project as a strategic asset — not just a design deliverable.",
  "ab.v1.title": "Performance First",
  "ab.v1.desc": "Every decision — from layout to code structure — is made with speed, usability and conversion in mind. We build for results, not just aesthetics.",
  "ab.v2.title": "CRO-Driven Design",
  "ab.v2.desc": "We apply Conversion Rate Optimization principles throughout the design process — mapping user flows, reducing friction and aligning every element to a clear business goal.",
  "ab.v3.title": "Global Reach",
  "ab.v3.desc": "We work with businesses ready to scale locally and internationally, building digital experiences that communicate clearly across markets and cultures.",
  "ab.cta.title": "Ready to work with us?",
  "ab.cta.sub": "Let's build a digital experience that actually performs and grows your business.",
  "ab.cta.btn": "Get in Touch",
  "ct.info.label": "Get in touch",
  "ct.info.title": "We'd love to hear about your project",
  "ct.info.desc": "Whether you need a new website, a landing page, SEO support or a full digital strategy — we're ready to help. Share your goals and we'll put together a tailored proposal.",
  "ct.card1.label": "Email",
  "ct.card1.note": "We usually respond within 24 hours",
  "ct.card2.label": "WhatsApp",
  "ct.card2.value": "Chat directly with us",
  "ct.card2.note": "Quick replies during business hours",
  "ct.card3.label": "Location",
  "ct.card3.value": "Remote — Worldwide",
  "ct.card3.note": "We work with clients globally",
  "ct.form.title": "Send a message",
  "ct.form.name": "Your name",
  "ct.form.name.ph": "John Smith",
  "ct.form.email": "Email address",
  "ct.form.email.ph": "you@company.com",
  "ct.form.company": "Company / Website URL",
  "ct.form.company.ph": "yourcompany.com",
  "ct.form.service": "Service you need",
  "ct.form.svc.default": "Select a service...",
  "ct.form.svc.web": "Web Design & Front-End Development",
  "ct.form.svc.seo": "SEO (Google)",
  "ct.form.svc.ecom": "E-Commerce Setup",
  "ct.form.svc.ads": "Paid Traffic (Meta Ads)",
  "ct.form.svc.full": "Full Digital Strategy",
  "ct.form.svc.other": "Other",
  "ct.form.msg": "Tell us about your project",
  "ct.form.msg.ph": "Describe your goals, timeline and any relevant details...",
  "ct.form.submit": "Demo Form →",
  "ct.form.note": "No spam. No commitments. Just a conversation about your project.",
  "case.fayson.label": "Portfolio Project",
  "case.fayson.hero.title": "Portfolio Website for <span class=\"accent\">Professional Photography</span>",
  "case.fayson.hero.sub": "A visual-first digital gallery designed to showcase artistic excellence and capture professional moments.",
  "case.fayson.overview.label": "Overview",
  "case.fayson.overview.title": "Visual excellence meets high-performance browsing.",
  "case.fayson.overview.text": "This project was developed as a premium platform concept for showcasing professional photography. The structure prioritizes visual quality, smooth navigation and a clear presentation experience.",
  "case.fayson.d1": "Custom gallery structure",
  "case.fayson.d2": "Image optimization for high resolution",
  "case.fayson.d3": "Responsive visual layout",
  "case.fayson.d4": "Smooth transitions and performance-oriented front-end",
  "case.fayson.strategy.label": "The Strategy",
  "case.fayson.strategy.title": "Designing for the eye of the artist.",
  "case.fayson.strategy.text1": "The layout was planned to let the photos speak for themselves. We reduced visual noise and created a minimalist flow that guides the visitor through the photographer's best work.",
  "case.fayson.strategy.text2": "The visual direction combines strong typography, dark premium aesthetics and clear content blocks to create a modern and memorable experience.",
  "case.fayson.gallery.label": "Visual Screens",
  "case.fayson.gallery.title": "Selected project views",
  "case.fayson.outcome.label": "Outcome",
  "case.fayson.outcome.title": "A polished stage for world-class photography.",
  "case.fayson.outcome.text": "The final result is a professional portfolio that enhances brand positioning and provides a seamless experience for potential clients and collaborators.",
  "case.fayson.back": "Back to Portfolio",
  "case.mansao.label": "Portfolio Project",
  "case.mansao.hero.title": "High-Converting LP for <span class=\"accent\">Premium Drinks</span>",
  "case.mansao.hero.sub": "A strategic sales experience built to connect a digital audience with premium beverage distribution.",
  "case.mansao.overview.label": "Overview",
  "case.mansao.overview.title": "Conversion-driven design for a massive digital brand.",
  "case.mansao.overview.text": "Built for a premium drinks brand, this landing page concept streamlines B2B communication and product presentation, turning digital attention into clear commercial intent for distributors and retailers.",
  "case.mansao.d1": "High-conversion content hierarchy",
  "case.mansao.d2": "B2B sales flow integration",
  "case.mansao.d3": "Scalable digital architecture",
  "case.mansao.d4": "Performance-focused user interface",
  "case.mansao.strategy.label": "The Strategy",
  "case.mansao.strategy.title": "Converting massive influence into sales.",
  "case.mansao.strategy.text1": "We designed a strategic path that guides the user from the brand's social recognition to the final purchase intent.",
  "case.mansao.strategy.text2": "The visual direction uses bold elements and clear content blocks to maintain the brand's energetic identity while presenting a professional and trust-building B2B environment.",
  "case.mansao.gallery.label": "Visual Screens",
  "case.mansao.gallery.title": "Selected project views",
  "case.mansao.outcome.label": "Outcome",
  "case.mansao.outcome.title": "A powerful sales engine for a digital giant.",
  "case.mansao.outcome.text": "This landing page serves as a strong foundation for marketing campaigns, helping convert digital traffic into business opportunities and clearer communication with commercial partners.",
  "case.mansao.back": "Back to Portfolio",
  "case.economy.label": "Portfolio Project",
  "case.economy.hero.title": "Newsletter LP for <span class=\"accent\">Digital Insights</span>",
  "case.economy.hero.sub": "A dynamic landing page designed to convert visitors into informed newsletter subscribers.",
  "case.economy.overview.label": "Overview",
  "case.economy.overview.title": "Speed and clarity for the future of finance.",
  "case.economy.overview.text": "Designed as a newsletter landing page concept, this project focuses on rapid information delivery and seamless subscription flows for a fast-moving digital audience.",
  "case.economy.d1": "Rapid subscription flow implementation",
  "case.economy.d2": "Content-first hierarchy",
  "case.economy.d3": "Web3 aesthetic integration",
  "case.economy.d4": "Optimized for speed and mobile browsing",
  "case.economy.strategy.label": "The Strategy",
  "case.economy.strategy.title": "Reducing friction in a fast-paced market.",
  "case.economy.strategy.text1": "The strategy focused on a clear value proposition: stay ahead of the game. Every block was placed to highlight the exclusivity of the newsletter's insights.",
  "case.economy.strategy.text2": "The visual direction combines modern typography with a clean, tech-focused aesthetic to create a trustworthy and professional information hub.",
  "case.economy.gallery.label": "Visual Screens",
  "case.economy.gallery.title": "Selected project views",
  "case.economy.outcome.label": "Outcome",
  "case.economy.outcome.title": "A direct gateway to the Web3 economy.",
  "case.economy.outcome.text": "The project delivers a fast, strategic subscription experience that supports community growth and reinforces the value of specialized digital content.",
  "case.economy.back": "Back to Portfolio",
  "case.mythoss.label": "Portfolio Project",
  "case.mythoss.hero.title": "Sophisticated LP for <span class=\"accent\">Premium Auto Services</span>",
  "case.mythoss.hero.sub": "An exclusive digital showcase for high-end automotive care, emphasizing performance and luxury.",
  "case.mythoss.overview.label": "Overview",
  "case.mythoss.overview.title": "Exclusivity and precision in every digital detail.",
  "case.mythoss.overview.text": "This project presents premium automotive services for owners of high-end vehicles. The page highlights value, trust, quality and a strong commitment to automotive performance.",
  "case.mythoss.d1": "Premium visual identity design",
  "case.mythoss.d2": "Service-focused content layout",
  "case.mythoss.d3": "Trust-building testimonial sections",
  "case.mythoss.d4": "Mobile-first luxury user experience",
  "case.mythoss.strategy.label": "The Strategy",
  "case.mythoss.strategy.title": "Communicating luxury through digital precision.",
  "case.mythoss.strategy.text1": "Every design decision was made to reflect the quality of the automotive services. We used a dark, premium aesthetic to match the high-end vehicles being serviced.",
  "case.mythoss.strategy.text2": "The visual direction combines strong typography with clear, high-quality content blocks to create a modern and memorable digital experience for discerning vehicle owners.",
  "case.mythoss.gallery.label": "Visual Screens",
  "case.mythoss.gallery.title": "Selected project views",
  "case.mythoss.outcome.label": "Outcome",
  "case.mythoss.outcome.title": "A digital standard for premium automotive care.",
  "case.mythoss.outcome.text": "A sophisticated digital presence that reinforces premium positioning, builds trust and communicates excellence in the high-end automotive service sector.",
  "case.mythoss.back": "Back to Portfolio",
  "pr.f2.btn2": "Any Doubts?"
};
