/* ============================================================
   OLK — PT TRANSLATIONS
   Public portfolio version
   ============================================================ */

window.OLK_TRANSLATIONS = window.OLK_TRANSLATIONS || {};
window.OLK_TRANSLATIONS.pt = {
  "nav.home": "Início",
  "nav.services": "Serviços",
  "nav.portfolio": "Portfólio",
  "nav.products": "Produtos",
  "nav.about": "Sobre",
  "nav.contact": "Contato",
  "footer.copy": "Copyright © 2026 OLK Web & SEO | Desenvolvido por OLK Web & SEO",
  "home.hero.eyebrow": "Estúdio de Web Design & SEO",
  "home.hero.title": "Projetando e Desenvolvendo <span class=\"bracket\">&lt;</span><span class=\"accent\">Sites de Alta Performance</span><span class=\"bracket\">&gt;</span> que Geram Crescimento Real.",
  "home.hero.sub": "Web Design, Desenvolvimento Front-end, E-commerce, SEO e Tráfego Pago para marcas em todo o mundo.",
  "home.hero.cta1": "Ver Trabalhos",
  "home.hero.cta2": "Entre em Contato",
  "home.brands.label": "Marcas que confiaram em nós",
  "home.services.label": "O que fazemos",
  "home.services.title": "Ajudamos marcas a criar experiências digitais rápidas, escaláveis e focadas em conversão.",
  "home.services.sub": "Do design e desenvolvimento ao tráfego e SEO — tudo feito com foco em performance.",
  "home.services.card1": "Web Design & Desenvolvimento Front-End",
  "home.services.card2": "Configuração de E-Commerce",
  "home.services.card3": "Tráfego Pago (Meta Ads)",
  "home.services.card4": "SEO (Otimização para Mecanismos de Busca) — Google",
  "home.services.cta": "Ver Todos os Serviços",
  "home.portfolio.label": "Trabalhos selecionados",
  "home.portfolio.title": "Uma seleção de projetos desenvolvidos para diferentes indústrias, mercados e modelos de negócio.",
  "home.portfolio.sub": "Sempre com foco em clareza, usabilidade e resultados.",
  "home.portfolio.p1.label": "Portfólio Fotográfico",
  "home.portfolio.p2.label": "Marca de Bebidas Premium",
  "home.portfolio.p3.label": "Landing Page de Newsletter",
  "home.portfolio.p4.label": "Marca Automotiva Premium",
  "home.portfolio.cta": "Ver Portfólio Completo",
  "home.about.label": "Sobre nós",
  "home.about.title": "Experiência que vai além do design",
  "home.about.body": "Desenvolvemos sites de alta performance e estratégias digitais em diferentes indústrias, combinando design, tecnologia e estratégia de marketing para entregar resultados reais.<br><br>Nossa abordagem foca em experiência do usuário, velocidade e conversão — garantindo que cada projeto seja não apenas visualmente forte, mas estrategicamente eficaz.",
  "home.about.s1.label": "Anos de experiência profissional",
  "home.about.s2.label": "Projetos entregues globalmente",
  "home.about.s3.label": "Abordagem focada em performance",
  "home.about.s4.label": "Indústrias atendidas no mundo todo",
  "home.teaser1.title": "Produtos Digitais",
  "home.teaser1.body": "Templates de landing page focados em conversão e produtos de design prontos para usar, criados para acelerar lançamentos e melhorar resultados.",
  "home.teaser1.cta": "Explorar Produtos",
  "home.teaser2.title": "Iniciar um Projeto",
  "home.teaser2.body": "Pronto para construir algo que realmente converte? Vamos falar sobre seus objetivos e criar uma experiência digital que performa.",
  "home.teaser2.cta": "Fale Conosco",
  "home.cta.title": "Vamos construir algo que realmente funciona.",
  "home.cta.sub": "Se você procura um site com clareza, performance e crescimento de longo prazo — vamos conversar.",
  "home.cta.btn": "Fale Conosco",
  "srv.hero.label": "O que oferecemos",
  "srv.hero.title": "<span class=\"accent\">Nossos</span> Serviços",
  "srv.hero.sub": "Ajudamos marcas a projetar, desenvolver e crescer com sites de alta performance. Nossos serviços cobrem todo o processo — da estrutura e código ao tráfego e visibilidade — sempre focados em resultados.",
  "srv.intro": "Cada projeto é abordado com uma <strong>mentalidade full-stack</strong>: consideramos design, desenvolvimento e marketing como um sistema unificado. O resultado é um site que tem ótima aparência, carrega rápido e <strong>converte</strong>.",
  "srv.s1.num": "01",
  "srv.s1.title": "Web Design & Desenvolvimento Front-End",
  "srv.s1.desc": "Design e desenvolvimento de sites modernos e responsivos voltados para performance e conversão.",
  "srv.s1.f1": "Layouts focados em UX/UI",
  "srv.s1.f2": "Código front-end limpo e escalável",
  "srv.s1.f3": "Design responsivo para todos os dispositivos",
  "srv.s1.f4": "Otimização de performance e velocidade de carregamento",
  "srv.s1.vtag": "Do Figma ao código pixel-perfect",
  "srv.s1.vnote": "Cada interface é criada com atenção ao fluxo do usuário, hierarquia visual e resultados de conversão mensuráveis.",
  "srv.s2.num": "02",
  "srv.s2.title": "SEO (Search Engine Optimization)",
  "srv.s2.desc": "SEO técnico e on-page para melhorar visibilidade e crescimento orgânico de longo prazo.",
  "srv.s2.f1": "Fundamentos de SEO técnico",
  "srv.s2.f2": "Otimização on-page",
  "srv.s2.f3": "Estrutura de conteúdo pronta para SEO",
  "srv.s2.f4": "Otimização de blog e páginas",
  "srv.s2.vtag": "Ranqueie mais alto. Cresça organicamente.",
  "srv.s2.vnote": "Criado para atrair tráfego qualificado ao longo do tempo — não apenas rankings, mas visitantes que realmente se convertem em clientes.",
  "srv.s3.num": "03",
  "srv.s3.title": "Perfil da Empresa no Google",
  "srv.s3.desc": "Visibilidade local criada para gerar crescimento, não apenas cliques.",
  "srv.s3.f1": "Configuração do Perfil da Empresa",
  "srv.s3.f2": "SEO local e alinhamento do perfil",
  "srv.s3.f3": "Otimização focada em conversão",
  "srv.s3.vtag": "Visibilidade local que converte",
  "srv.s3.vnote": "Perfis pensados para a jornada local — da primeira busca até a decisão final de contato.",
  "srv.s4.num": "04",
  "srv.s4.title": "Configuração de E-Commerce",
  "srv.s4.desc": "Configuração e otimização de lojas online criadas para escalar e converter.",
  "srv.s4.f1": "Lojas Shopify & WooCommerce",
  "srv.s4.f2": "Estrutura de produtos e coleções",
  "srv.s4.f3": "Otimização de checkout",
  "srv.s4.f4": "Layouts focados em conversão",
  "srv.s4.vtag": "Lojas feitas para vender",
  "srv.s4.vnote": "Cada detalhe do fluxo de compra é projetado para reduzir atritos e maximizar a receita por visitante.",
  "srv.cta.title": "Pronto para iniciar seu projeto?",
  "srv.cta.sub": "Vamos conversar sobre o que sua marca precisa — e construir do jeito certo.",
  "srv.cta.btn": "Fale Conosco",
  "pf.hero.label": "Projetos do portfólio",
  "pf.hero.title": "<span class=\"accent\">Trabalhos</span> Selecionados",
  "pf.hero.sub": "Projetos desenvolvidos para marcas, criadores e empresas em múltiplas indústrias. Cada um representa uma abordagem cuidadosa de design, código e estratégia — focada em clareza, performance e crescimento de longo prazo.",
  "pf.p1.num": "Projeto 01",
  "pf.p1.cat": "Portfólio Fotográfico",
  "pf.p1.title": "Website de Portfólio Fotográfico",
  "pf.p1.desc": "Um conceito completo de site de portfólio criado para apresentar trabalhos visuais com estética limpa, editorial e focada em impacto, clareza e experiência do usuário.",
  "pf.p1.t1": "Web Design",
  "pf.p1.t2": "Desenvolvimento Front-End",
  "pf.p1.t3": "Portfólio",
  "pf.p1.link": "Ver Projeto",
  "pf.p2.num": "Projeto 02",
  "pf.p2.cat": "Marca de Bebidas Premium",
  "pf.p2.title": "Landing Page para Marca de Bebidas Premium",
  "pf.p2.desc": "Um conceito de landing page de alta conversão para uma marca de bebidas premium, estruturado para apoiar apresentação de produto, interesse de distribuidores e crescimento comercial.",
  "pf.p2.t1": "Landing Page",
  "pf.p2.t2": "E-Commerce",
  "pf.p2.t3": "Conversão CRO",
  "pf.p2.link": "Ver Projeto",
  "pf.p3.num": "Projeto 03",
  "pf.p3.cat": "Landing Page de Newsletter",
  "pf.p3.title": "Landing Page para Assinatura de Newsletter",
  "pf.p3.desc": "Um conceito de landing page focado em newsletter, criado para comunicar valor e gerar inscrições com layout claro, direto e estrutura de copy persuasiva.",
  "pf.p3.t1": "Landing Page",
  "pf.p3.t2": "Newsletter",
  "pf.p3.t3": "Geração de Leads",
  "pf.p3.link": "Ver Projeto",
  "pf.p4.num": "Projeto 04",
  "pf.p4.cat": "Marca Automotiva Premium",
  "pf.p4.title": "Landing Page para Marca Automotiva Premium",
  "pf.p4.desc": "Um conceito de landing page sofisticado para apresentar serviços automotivos de alto padrão com clareza, confiança e uma experiência digital premium.",
  "pf.p4.t1": "Landing Page",
  "pf.p4.t2": "Luxo",
  "pf.p4.t3": "Automotivo",
  "pf.p4.link": "Ver Projeto",
  "pf.cta.title": "Tem um projeto em mente?",
  "pf.cta.sub": "Vamos construir algo que performa tão bem quanto parece.",
  "pf.cta.btn": "Fale Conosco",
  "pr.f1.kicker": "Ativos digitais",
  "pr.f1.title": "Templates Figma, Mockups & Produtos de Design",
  "pr.f1.desc": "Produtos digitais premium criados para conversão. Use esses templates para lançar mais rápido, apresentar melhor o seu trabalho e melhorar seus resultados sem começar do zero.",
  "pr.f1.btn1": "Comprar Agora",
  "pr.f1.btn2": "Dúvidas?",
  "pr.f2.kicker": "Landing Pages",
  "pr.f2.title": "Templates de Landing Page Prontos para Converter",
  "pr.f2.desc": "Templates de landing page totalmente estruturados e criados para performance. Cada template é projetado com princípios de CRO — headlines otimizadas, CTAs claros e layouts que guiam o visitante à conversão.",
  "pr.f2.btn1": "Comprar Agora",
  "pr.cta.title": "Precisa de algo feito sob medida?",
  "pr.cta.sub": "Desenvolvemos experiências digitais personalizadas para marcas que querem crescer. Vamos conversar.",
  "pr.cta.btn": "Fale Conosco",
  "ab.who.eyebrow": "Sobre a OLK",
  "ab.who.title": "Quem Somos",
  "ab.who.p1": "A OLK é um estúdio de web design e desenvolvimento front-end orientado a performance, focado em criar experiências digitais de alta conversão.",
  "ab.who.p2": "Trabalhamos com empresas que querem mais do que apenas um site — querem crescimento. Combinando design, tecnologia e estratégia de marketing, criamos sites, landing pages e estruturas de SEO feitas para performar.",
  "ab.who.p3": "Nosso trabalho é focado em experiência do usuário, velocidade e conversão, garantindo que cada projeto seja não apenas visualmente forte, mas estrategicamente eficaz.",
  "ab.who.p4": "Ajudamos marcas a transformar tráfego em receita.",
  "ab.why.eyebrow": "Por que a OLK",
  "ab.why.title": "Por que nos Escolher",
  "ab.why.subtitle": "Abordagem Focada em Performance",
  "ab.why.body": "Não apenas construímos sites — construímos ativos digitais criados para gerar leads, aumentar conversões e escalar negócios.<br><br>Nosso processo combina CRO (Otimização de Taxa de Conversão), desenvolvimento front-end limpo e decisões baseadas em dados para entregar resultados reais.",
  "ab.why.s1.num": "6+",
  "ab.why.s1.label": "Anos de Experiência",
  "ab.why.s2.num": "100+",
  "ab.why.s2.label": "Projetos Entregues",
  "ab.why.s3.label": "Foco em Clientes Globais",
  "ab.val.label": "Nossa abordagem",
  "ab.val.title": "O que nos diferencia",
  "ab.val.sub": "Tratamos cada projeto como um ativo estratégico — não apenas uma entrega de design.",
  "ab.v1.title": "Performance em Primeiro Lugar",
  "ab.v1.desc": "Cada decisão — do layout à estrutura de código — é tomada com velocidade, usabilidade e conversão em mente. Construímos para resultados, não apenas para estética.",
  "ab.v2.title": "Design Orientado a CRO",
  "ab.v2.desc": "Aplicamos os princípios de Otimização de Taxa de Conversão em todo o processo de design — mapeando fluxos de usuário, reduzindo atritos e alinhando cada elemento a um objetivo claro de negócio.",
  "ab.v3.title": "Alcance Global",
  "ab.v3.desc": "Trabalhamos com empresas prontas para escalar local e internacionalmente, criando experiências digitais que se comunicam claramente em diferentes mercados e culturas.",
  "ab.cta.title": "Pronto para trabalhar conosco?",
  "ab.cta.sub": "Vamos construir uma experiência digital que realmente performa e faz seu negócio crescer.",
  "ab.cta.btn": "Entre em Contato",
  "ct.info.label": "Entre em contato",
  "ct.info.title": "Adoraríamos ouvir sobre seu projeto",
  "ct.info.desc": "Seja um novo site, uma landing page, suporte de SEO ou uma estratégia digital completa — estamos prontos para ajudar. Compartilhe seus objetivos e montaremos uma proposta personalizada.",
  "ct.card1.label": "E-mail",
  "ct.card1.note": "Geralmente respondemos em até 24 horas",
  "ct.card2.label": "WhatsApp",
  "ct.card2.value": "Converse diretamente conosco",
  "ct.card2.note": "Respostas rápidas durante o horário comercial",
  "ct.card3.label": "Localização",
  "ct.card3.value": "Remoto — Mundial",
  "ct.card3.note": "Trabalhamos com clientes em todo o mundo",
  "ct.form.title": "Envie uma mensagem",
  "ct.form.name": "Seu nome",
  "ct.form.name.ph": "João Silva",
  "ct.form.email": "Endereço de e-mail",
  "ct.form.email.ph": "voce@empresa.com",
  "ct.form.company": "Empresa / URL do site",
  "ct.form.company.ph": "suaempresa.com",
  "ct.form.service": "Serviço que precisa",
  "ct.form.svc.default": "Selecione um serviço...",
  "ct.form.svc.web": "Web Design & Desenvolvimento Front-End",
  "ct.form.svc.seo": "SEO (Google)",
  "ct.form.svc.ecom": "Configuração de E-Commerce",
  "ct.form.svc.ads": "Tráfego Pago (Meta Ads)",
  "ct.form.svc.full": "Estratégia Digital Completa",
  "ct.form.svc.other": "Outro",
  "ct.form.msg": "Fale sobre seu projeto",
  "ct.form.msg.ph": "Descreva seus objetivos, prazo e quaisquer detalhes relevantes...",
  "ct.form.submit": "Formulário Demo →",
  "ct.form.note": "Sem spam. Sem compromissos. Apenas uma conversa sobre seu projeto.",
  "case.fayson.label": "Projeto de Portfólio",
  "case.fayson.hero.title": "Website de Portfólio para <span class=\"accent\">Fotografia Profissional</span>",
  "case.fayson.hero.sub": "Uma galeria digital visual-first criada para destacar excelência artística e capturar momentos profissionais.",
  "case.fayson.overview.label": "Visão Geral",
  "case.fayson.overview.title": "Excelência visual com navegação de alta performance.",
  "case.fayson.overview.text": "Este projeto foi desenvolvido como um conceito de plataforma premium para apresentar fotografia profissional. A estrutura prioriza qualidade visual, navegação fluida e uma experiência de apresentação clara.",
  "case.fayson.d1": "Estrutura de galeria personalizada",
  "case.fayson.d2": "Otimização de imagens em alta resolução",
  "case.fayson.d3": "Layout visual responsivo",
  "case.fayson.d4": "Transições suaves e front-end orientado à performance",
  "case.fayson.strategy.label": "A Estratégia",
  "case.fayson.strategy.title": "Design pensado para o olhar do artista.",
  "case.fayson.strategy.text1": "O layout foi planejado para permitir que as fotografias falem por si. Reduzimos ruídos visuais e criamos um fluxo minimalista que guia o visitante pelo melhor trabalho do fotógrafo.",
  "case.fayson.strategy.text2": "A direção visual combina tipografia forte, estética premium escura e blocos de conteúdo claros para criar uma experiência moderna e memorável.",
  "case.fayson.gallery.label": "Telas Visuais",
  "case.fayson.gallery.title": "Visualizações selecionadas do projeto",
  "case.fayson.outcome.label": "Resultado",
  "case.fayson.outcome.title": "Um palco refinado para fotografia de alto nível.",
  "case.fayson.outcome.text": "O resultado final é um portfólio profissional que fortalece o posicionamento da marca e oferece uma experiência fluida para potenciais clientes e colaboradores.",
  "case.fayson.back": "Voltar ao Portfólio",
  "case.mansao.label": "Projeto de Portfólio",
  "case.mansao.hero.title": "Landing Page de Alta Conversão para <span class=\"accent\">Bebidas Premium</span>",
  "case.mansao.hero.sub": "Uma experiência estratégica de vendas criada para conectar uma audiência digital à distribuição de bebidas premium.",
  "case.mansao.overview.label": "Visão Geral",
  "case.mansao.overview.title": "Design orientado à conversão para uma grande marca digital.",
  "case.mansao.overview.text": "Criada para uma marca de bebidas premium, esta landing page conceitual simplifica a comunicação B2B e a apresentação de produto, transformando atenção digital em intenção comercial clara para distribuidores e varejistas.",
  "case.mansao.d1": "Hierarquia de conteúdo de alta conversão",
  "case.mansao.d2": "Integração de fluxo de vendas B2B",
  "case.mansao.d3": "Arquitetura digital escalável",
  "case.mansao.d4": "Interface focada em performance",
  "case.mansao.strategy.label": "A Estratégia",
  "case.mansao.strategy.title": "Convertendo grande influência em vendas.",
  "case.mansao.strategy.text1": "Criamos um caminho estratégico que guia o usuário do reconhecimento social da marca até a intenção final de compra.",
  "case.mansao.strategy.text2": "A direção visual usa elementos fortes e blocos de conteúdo claros para manter a identidade energética da marca, ao mesmo tempo em que apresenta um ambiente B2B profissional e confiável.",
  "case.mansao.gallery.label": "Telas Visuais",
  "case.mansao.gallery.title": "Visualizações selecionadas do projeto",
  "case.mansao.outcome.label": "Resultado",
  "case.mansao.outcome.title": "Um poderoso motor de vendas para uma gigante digital.",
  "case.mansao.outcome.text": "Esta landing page serve como uma base sólida para campanhas de marketing, ajudando a converter tráfego digital em oportunidades comerciais e comunicação mais clara com parceiros.",
  "case.mansao.back": "Voltar ao Portfólio",
  "case.economy.label": "Projeto de Portfólio",
  "case.economy.hero.title": "Landing Page Newsletter para <span class=\"accent\">Insights Digitais</span>",
  "case.economy.hero.sub": "Uma landing page dinâmica criada para converter visitantes em assinantes informados.",
  "case.economy.overview.label": "Visão Geral",
  "case.economy.overview.title": "Velocidade e clareza para o futuro das finanças.",
  "case.economy.overview.text": "Criado como conceito de landing page para newsletter, este projeto foca em entrega rápida de informação e fluxos de inscrição simplificados para uma audiência digital em ritmo acelerado.",
  "case.economy.d1": "Fluxo rápido de inscrição",
  "case.economy.d2": "Hierarquia focada em conteúdo",
  "case.economy.d3": "Integração estética Web3",
  "case.economy.d4": "Otimizado para velocidade e mobile",
  "case.economy.strategy.label": "A Estratégia",
  "case.economy.strategy.title": "Reduzindo fricção em um mercado acelerado.",
  "case.economy.strategy.text1": "A estratégia focou em uma proposta de valor clara: estar à frente do mercado. Cada bloco foi posicionado para destacar a exclusividade dos insights da newsletter.",
  "case.economy.strategy.text2": "A direção visual combina tipografia moderna com uma estética limpa e tecnológica para criar um hub de informação confiável e profissional.",
  "case.economy.gallery.label": "Telas Visuais",
  "case.economy.gallery.title": "Visualizações selecionadas do projeto",
  "case.economy.outcome.label": "Resultado",
  "case.economy.outcome.title": "Uma porta direta para a economia Web3.",
  "case.economy.outcome.text": "O projeto entrega uma experiência de assinatura rápida e estratégica que apoia o crescimento da comunidade e reforça o valor de conteúdo digital especializado.",
  "case.economy.back": "Voltar ao Portfólio",
  "case.mythoss.label": "Projeto de Portfólio",
  "case.mythoss.hero.title": "Landing Page Sofisticada para <span class=\"accent\">Serviços Automotivos Premium</span>",
  "case.mythoss.hero.sub": "Uma vitrine digital exclusiva para cuidados automotivos de alto padrão, enfatizando performance e luxo.",
  "case.mythoss.overview.label": "Visão Geral",
  "case.mythoss.overview.title": "Exclusividade e precisão em cada detalhe digital.",
  "case.mythoss.overview.text": "Este projeto apresenta serviços automotivos premium para proprietários de veículos de alto padrão. A página destaca valor, confiança, qualidade e compromisso com performance automotiva.",
  "case.mythoss.d1": "Design de identidade visual premium",
  "case.mythoss.d2": "Layout focado em serviços",
  "case.mythoss.d3": "Seções para construção de confiança",
  "case.mythoss.d4": "Experiência mobile-first de luxo",
  "case.mythoss.strategy.label": "A Estratégia",
  "case.mythoss.strategy.title": "Comunicando luxo através da precisão digital.",
  "case.mythoss.strategy.text1": "Cada decisão de design foi tomada para refletir a qualidade dos serviços automotivos. Utilizamos uma estética premium escura para acompanhar o padrão dos veículos atendidos.",
  "case.mythoss.strategy.text2": "A direção visual combina tipografia forte com blocos de conteúdo claros e sofisticados para criar uma experiência digital moderna e memorável.",
  "case.mythoss.gallery.label": "Telas Visuais",
  "case.mythoss.gallery.title": "Visualizações selecionadas do projeto",
  "case.mythoss.outcome.label": "Resultado",
  "case.mythoss.outcome.title": "Um padrão digital para cuidados automotivos premium.",
  "case.mythoss.outcome.text": "Uma presença digital sofisticada que reforça posicionamento premium, gera confiança e comunica excelência no setor automotivo de alto padrão.",
  "case.mythoss.back": "Voltar ao Portfólio",
  "pr.f2.btn2": "Dúvidas?"
};
